---
abstract: 'HTML5 based GUI for Perl Node Interface'
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PNI-GUI
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 0
  File::Spec: 0
  Mojolicious: 2.42
version: v0.02.0
